#!/bin/bash
clear
echo "Подсчёт файлов при помощи find и wc"
sleep 2
echo "Please, write directory necessary!!"
read dir
res=$(find $dir -maxdepth 1 -type f | wc | sed 's/   /\n/g' | sed "1d;3d;4d;5d")
echo "Количество файлов в директории '$dir':$res"
